### ISSUE TITLE
What does the histogram in feature info page indicate?

### ISSUE THREAD

**Issue by ptyin** [openai/sparse_autoencoder#1]
I cannot find explanation for that figure. Is that a [Feature Density Histogram](https://transformer-circuits.pub/2023/monosemantic-features#appendix-feature-density)?

**Comment by ptyin** [comment]
Got it. The x axis indicates activation value, and the y is for token counts, right?

<img width="791" alt="image" src="https://github.com/openai/sparse_autoencoder/assets/32592585/23cf5e02-5e01-4815-aba8-7d3a7befdb8c">

**Comment by zdaiot** [comment]
@ptyin I think so too. Do you know what "Prediction prior to ablated token" means? Why do most of the words here show as "Prediction prior to ablated token", and only a small part show as KL divergence?

![image](https://github.com/openai/sparse_autoencoder/assets/40540467/03c70c90-eb5b-4f0b-b6d3-a358b386712b)

**Comment by WuTheFWasThat** [comment]
@ptyin yes that's correct!

@zdaiot "Prediction prior to ablated token" is because we're showing effects when ablating the boxed token.  All predictions of tokens up to the ablated token are unaffected
