### ISSUE TITLE
GPT-2 autoencoder checkpoint?

### ISSUE THREAD

**Issue by GheorgheMorari** [openai/sparse_autoencoder#4]
Will a checkpoint be released for the gpt-2 sparse autoencoder alongside the training code?
If not, how much vram is approximatively needed for the training for the gpt-2 autoencoder model?

**Comment by WuTheFWasThat** [comment]
yes, they are released.  see https://github.com/openai/sparse_autoencoder/blob/main/sparse_autoencoder/paths.py
