### ISSUE TITLE
Understanding table output

### ISSUE THREAD

**Issue by lastonehome** [openai/sparse_autoencoder#5]
Hi,

thanks for publishing this. Can I check I understand the output in the tables, please? The docid I’m assuming relates to a specific output from the model from a given prompt? And the token id is related to the prompt itself?

![image](https://github.com/openai/sparse_autoencoder/assets/131170971/b03e41c9-31da-4bd8-a4e5-349ecc36207b)

Apologies if these are simple questions. Interested in explainable AI more than the technical ins and outs.

**Comment by WuTheFWasThat** [comment]
docid is just an ID of the document from a dataset.  It is **not** a model output, most likely human-written from the internet

the token ID is just the index of the activated token.  for example if token was 0, it would mean that the first token had a positive activation
